apiVersion: v1
kind: ConfigMap
metadata:
  name: fluxora-config
data:
  API_URL: http://app-backend
  REDIS_HOST: fluxora-redis
  REDIS_PORT: "6379"
  DATABASE_HOST: fluxora-database
  DATABASE_PORT: "3306"
  DATABASE_NAME: fluxoradb
  DATABASE_USER: appuser
  LOG_LEVEL: debug
